#!/bin/bash
# MATE on X11 — primary supported Duo desktop for this repo.
ZENBOOK_PROFILE_LABEL="MATE / X11"
ZENBOOK_PROFILE_SOFTKBD=(onboard florence maliit-keyboard)
ZENBOOK_PROFILE_TOUCH=x11
ZENBOOK_PROFILE_MIRROR=x11
ZENBOOK_PROFILE_WINDOWS=wmctrl
ZENBOOK_PROFILE_DISPLAY_TOOL=xrandr
