#!/bin/bash
ZENBOOK_PROFILE_LABEL="wlroots / Wayland"
ZENBOOK_PROFILE_SOFTKBD=(squeekboard maliit-keyboard onboard)
ZENBOOK_PROFILE_TOUCH=none
ZENBOOK_PROFILE_MIRROR=wlr
ZENBOOK_PROFILE_WINDOWS=none
ZENBOOK_PROFILE_DISPLAY_TOOL=wlr-randr
